### ISSUE TITLE
请问是Graph FPN的原作者吗？

### ISSUE THREAD

**Issue by lhcezx** [GangmingZhao/GraphFPN-Graph-Feature-Pyramid-Network-for-Object-Detection#6]
您好，这边看到了您在github仓库里发的代码中的graph-fpn-main.zip是我在去年11月份开始做的一直做到今年的一月份的一个学校project，当时您的代码还为开源，我这边自己手动尝试做了一些复现。很高兴我的代码能被您引用，可以麻烦您在readme中加入我的链接吗？
https://github.com/lhcezx/Graph-FPN.git

**Comment by GangmingZhao** [comment]
您好，很开心能看到您在复现我们的graphFPN。我在github发现您写的代码非常漂亮优雅，所以就直接使用作为base version。我会在readme中加入您的link并加以说明。如果有机会也想和您保持沟通交流，对graphFPN作进一步的推广，而且后期可能会有很多research project也希望有机会和您合作。我的email：gangmingzhao@gmail.com

**Comment by lhcezx** [comment]
您好，非常感谢您的答复，通过阅读您的文章使我对图神经网络获得了进一步的了解和认知，和FPN网络的结合更是精妙至极。我也非常期待和您保持交流并在学习之余能继续这个项目。如果有任何我能帮到的地方，您可以随时联系我lhcezx@gmail.com，预祝您的科研之路更加顺利。

**Comment by GangmingZhao** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        随时交流，如果您使用wechat或者skype，可以给我一个您的账号。方便的话 我可以加您为好友，更方便做科研交流，如果不方便，随时email沟通即可。
        
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2022年8月9日 16:50
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [GangmingZhao/GraphFPN-Graph-Feature-Pyramid-Network-for-Object-Detection] 请问是Graph FPN的原作者吗？ (Issue #6)
        
      
    
  
  
***@***.***，预祝您的科研之路更加顺利。

**Comment by lhcezx** [comment]
> font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } 随时交流，如果您使用wechat或者skype，可以给我一个您的账号。方便的话 我可以加您为好友，更方便做科研交流，如果不方便，随时email沟通即可。 ***@***.***
> […](#)
> ---- 回复的原邮件 ---- 发件人 ***@***.***> 发送日期 2022年8月9日 16:50 收件人 ***@***.***> 抄送人 ***@***.***> , ***@***.***> 主题 Re: [GangmingZhao/GraphFPN-Graph-Feature-Pyramid-Network-for-Object-Detection] 请问是Graph FPN的原作者吗？ (Issue #6) ***@***.***，预祝您的科研之路更加顺利。 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

lhc_burger是我的wechat，您可以随时加我
